# Generated by Django 4.0 on 2021-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
