# Generated by Django 4.0 on 2021-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_blogs', '0003_question_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ids',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
